name: Run Unit Tests

on: [push] # This defines WHEN the workflow runs (on a push event)

jobs: # Defines the jobs in this workflow
  run-unit-test: # This is the ID of your job
    runs-on: ubuntu-latest # This is the REQUIRED runner environment for this job, notice the indentation
    name: Unit Tests # This is an OPTIONAL, human-readable name for the job

    steps: # Defines the steps within this job
      - uses: actions/checkout@v4 # Action to check out your repository code

      - uses: actions/setup-node@v4 # Action to set up Node.js environment
        with:
          node-version: 18
          cache: 'npm' # Caches node modules for faster builds

      - name: Install dependencies # Step to install project dependencies
        run: npm ci

      - name: Run tests # Step to execute your tests
        run: npm run test